# Create a Class to Create, retrieve, update, and 
# delete employee details from the dictionary. 

#     Employee details are ID, Name, DOB, Blood Group, and Address. 
# (Validate all the details are in the correct format)
#     ID should be created by the class for the new employee created 
# dynamically. other details can be given while creating the object. 
#     Should able to retrieve employee details by name or by ID or by both
#  information. 
#     Delete employee details should work with employee ID or name. if a 
# Duplicate name is available should ask for an ID. Always ask for 
# confirmation while deleting
# Questions 2:
# Write a class for banking operations like, Balance Check, Deposit, Withdraw.
# Bank details should have Name, Account number, age, etc. If the age is less than 18, it should not allow to create account
# Acoount number should be generated by class dynamically. It should not be a duplicate one

